__title__ = 'tiffs'
__version__ = '0.0.1'
__author__ = 'Eric Upschulte'
__email__ = 'e.upschulte@fz-juelich.de'
__license__ = 'Apache License, Version 2.0'
__summary__ = 'Simple interface for stacked Tiffs.'
__url__ = __uri__ = ''
